import Head from 'next/head'
import Featured from '../components/Featured'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Booking.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <div className="mt-[50px] flex flex-col gap-[30px] items-center">
        <Featured />
      </div>
    </div>
  )
}
